<?php
return array(
    'key' => 'layout_64919172a223e',
    'name' => 'faqs',
    'label' => 'FAQs',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_64919173a223f',
            'label' => 'Settings',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_64919173a2240',
            'label' => 'Background',
            'name' => 'background',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'primary' => 'Primary',
                'secondary' => 'Secondary',
                'tertiary' => 'Tertiary',
                'light-grey' => 'Light Grey',
                'white' => 'White',
            ),
            'default_value' => 'white',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_64919173a2243',
            'label' => 'Padding',
            'name' => 'padding',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_64919173a2244',
                    'label' => 'Top',
                    'name' => 'top',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_64919173a2245',
                    'label' => 'Bottom',
                    'name' => 'bottom',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_64919173a2246',
                    'label' => '',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<strong>Set a value 0-5.</strong>
0 = 0px | 1 = 20px | 2 = 40px | 3 = 60px | 4 = 80px | 5 = 100px',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_64919173a2247',
            'label' => 'Content',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_64919173a2249',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_649191aaa2255',
            'label' => 'Questions & Answers',
            'name' => 'questions_answers',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'table',
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_649191bfa2256',
                    'label' => 'Question',
                    'name' => 'question',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent_repeater' => 'field_649191aaa2255',
                ),
                array(
                    'key' => 'field_649191cea2257',
                    'label' => 'Answer',
                    'name' => 'answer',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent_repeater' => 'field_649191aaa2255',
                ),
            ),
        ),
    ),
    'min' => '',
    'max' => '',
);
