<?php
return array(
    'key' => 'layout_64415098a68fc',
    'name' => 'grid',
    'label' => 'Grid',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_6441509da68fe',
            'label' => 'Settings',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_644150b0a6900',
            'label' => 'Style',
            'name' => 'style',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'default' => 'Default',
                'icon-links' => 'Icon Links',
                'image-links' => 'Image Links - Simple',
                'image-links-detailed' => 'Image Links - Detailed',
                'logos' => 'Logos',
            ),
            'default_value' => 'default',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_646b6ff651765',
            'label' => 'Layout',
            'name' => 'layout',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_644150b0a6900',
                        'operator' => '==',
                        'value' => 'donations',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'flat' => 'Flat',
                'raised' => 'Raised Centre',
            ),
            'default_value' => 'flat',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_644150dda6901',
            'label' => 'Background',
            'name' => 'background',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'primary' => 'Primary',
                'secondary' => 'Secondary',
                'tertiary' => 'Tertiary',
                'light-grey' => 'Light Grey',
                'white' => 'White',
            ),
            'default_value' => 'white',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6480a12bc207e',
            'label' => 'Padding',
            'name' => 'padding',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6480a12bc207f',
                    'label' => 'Top',
                    'name' => 'top',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6480a12bc2080',
                    'label' => 'Bottom',
                    'name' => 'bottom',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6480a12bc2081',
                    'label' => '',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<strong>Set a value 0-5.</strong>
0 = 0px | 1 = 20px | 2 = 40px | 3 = 60px | 4 = 80px | 5 = 100px',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_644150a4a68ff',
            'label' => 'Content',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_644153aca6902',
            'label' => '',
            'name' => 'image_links',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_644150b0a6900',
                        'operator' => '==',
                        'value' => 'image-links',
                    ),
                ),
                array(
                    array(
                        'field' => 'field_644150b0a6900',
                        'operator' => '==',
                        'value' => 'icon-links',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'table',
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_644153d1a6903',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'parent_repeater' => 'field_644153aca6902',
                ),
                array(
                    'key' => 'field_644153e2a6904',
                    'label' => 'Display Text',
                    'name' => 'display_text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_644153aca6902',
                ),
                array(
                    'key' => 'field_644153f9a6905',
                    'label' => 'Link',
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_644153aca6902',
                ),
                array(
                    'key' => 'field_64415400a6906',
                    'label' => 'Open in New Tab',
                    'name' => 'open_in_new_tab',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_644153aca6902',
                ),
            ),
        ),
        array(
            'key' => 'field_652533c2b4700',
            'label' => '',
            'name' => 'image_links_detailed',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_644150b0a6900',
                        'operator' => '==',
                        'value' => 'image-links-detailed',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_652533c2b4701',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'parent_repeater' => 'field_652533c2b4700',
                ),
                array(
                    'key' => 'field_652533c2b4703',
                    'label' => 'Link',
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '60',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_652533c2b4700',
                ),
                array(
                    'key' => 'field_652533c2b4704',
                    'label' => 'Open in New Tab',
                    'name' => 'open_in_new_tab',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_652533c2b4700',
                ),
                array(
                    'key' => 'field_652533c2b4702',
                    'label' => 'Display Text',
                    'name' => 'display_text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_652533c2b4700',
                ),
                array(
                    'key' => 'field_652534d6da0ac',
                    'label' => 'Description',
                    'name' => 'description',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'rows' => 3,
                    'placeholder' => '',
                    'new_lines' => '',
                    'parent_repeater' => 'field_652533c2b4700',
                ),
            ),
        ),
        array(
            'key' => 'field_6489d67e68ec7',
            'label' => '',
            'name' => 'items',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_644150b0a6900',
                        'operator' => '==',
                        'value' => 'default',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_6489d67e68ec9',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '80',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_6489d67e68ec7',
                ),
                array(
                    'key' => 'field_6489d67e68ec8',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'parent_repeater' => 'field_6489d67e68ec7',
                ),
                array(
                    'key' => 'field_6489d6c468ecc',
                    'label' => 'Text',
                    'name' => 'text',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'rows' => 4,
                    'placeholder' => '',
                    'new_lines' => '',
                    'parent_repeater' => 'field_6489d67e68ec7',
                ),
                array(
                    'key' => 'field_64f1fb1d6172d',
                    'label' => 'Button',
                    'name' => 'button',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_643e971cd877b',
                                'operator' => '==',
                                'value' => 'standard',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'parent_repeater' => 'field_6489d67e68ec7',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_64f1fb1e6172e',
                            'label' => 'Enabled',
                            'name' => 'enabled',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 1,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e6172f',
                            'label' => 'Open In New Tab',
                            'name' => 'open_in_new_tab',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e61730',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'arrow-right' => 'Arrow (Right)',
                                'arrow-left' => 'Arrow (Left)',
                                'heart' => 'Heart',
                            ),
                            'default_value' => 'null',
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 1,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e61731',
                            'label' => 'Icon Location',
                            'name' => 'icon_location',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_64f1fb1e61730',
                                        'operator' => '!=',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'before' => 'Before Text',
                                'after' => 'After Text',
                            ),
                            'default_value' => false,
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e61732',
                            'label' => 'Display Text',
                            'name' => 'display_text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '75',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e61733',
                            'label' => 'Background',
                            'name' => 'colour',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'primary' => 'Primary',
                                'secondary' => 'Secondary',
                                'tertiary' => 'Tertiary',
                                'light-grey' => 'Light Grey',
                                'white' => 'White',
                                'outline-primary' => 'Outline - Primary',
                                'outline-secondary' => 'Outline - Secondary',
                                'outline-tertiary' => 'Outline - Tertiary',
                                'outline-light-grey' => 'Outline - Light Grey',
                                'outline-white' => 'Outline - White',
                            ),
                            'default_value' => 'primary',
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e61734',
                            'label' => 'Link',
                            'name' => 'link',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '75',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_64f1fb1e61735',
                            'label' => 'Hover',
                            'name' => 'hover',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'hover-primary' => 'Primary',
                                'hover-secondary' => 'Secondary',
                                'hover-tertiary' => 'Tertiary',
                                'hover-light-grey' => 'Light Grey',
                                'hover-white' => 'White',
                                'hover-outline-primary' => 'Outline - Primary',
                                'hover-outline-secondary' => 'Outline - Secondary',
                                'hover-outline-tertiary' => 'Outline - Tertiary',
                                'hover-outline-light-grey' => 'Outline - Light Grey',
                                'hover-outline-white' => 'Outline - White',
                            ),
                            'default_value' => 'hover-secondary',
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_651ec6bfc1965',
            'label' => '',
            'name' => 'logos',
            'aria-label' => '',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_644150b0a6900',
                        'operator' => '==',
                        'value' => 'logos',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'insert' => 'append',
            'preview_size' => 'medium',
        ),
    ),
    'min' => '',
    'max' => '',
);
