<?php
return array(
    'key' => 'layout_6448fa8d386f8',
    'name' => 'split_content',
    'label' => 'Split Content',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_6448fb41386fa',
            'label' => 'Settings',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_644a4ead79f42',
            'label' => 'Background',
            'name' => 'background',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'primary' => 'Primary',
                'secondary' => 'Secondary',
                'tertiary' => 'Tertiary',
                'light-grey' => 'Light Grey',
                'white' => 'White',
            ),
            'default_value' => 'white',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6448fc59051e4',
            'label' => 'Split Order',
            'name' => 'split_order',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'one-two' => 'Split One | Split Two',
                'two-one' => 'Split Two | Split One',
            ),
            'default_value' => 'one-two',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_64be82c13947f',
            'label' => 'Split Alignment',
            'name' => 'split_alignment',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '34',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'align-items-start' => 'Top',
                'align-items-center' => 'Centre',
                'align-items-end' => 'Bottom',
            ),
            'default_value' => 'align-items-center',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6526af1634705',
            'label' => 'Content Width',
            'name' => 'content_width',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'standard' => 'Standard',
                'slim' => 'Slim',
            ),
            'default_value' => 'standard',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6448fb99386fc',
            'label' => 'Split One',
            'name' => 'split_one_content_type',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'carousel' => 'Content Carousel',
                'image' => 'Image',
                'image_carousel' => 'Image Carousel',
                'map' => 'Map',
                'text' => 'Text',
                'video' => 'Video'
            ),
            'default_value' => 'image',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_644a4fb9d93e8',
            'label' => 'Split Two',
            'name' => 'split_two_content_type',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'carousel' => 'Content Carousel',
                'image' => 'Image',
                'image_carousel' => 'Image Carousel',
                'map' => 'Map',
                'text' => 'Text',
            ),
            'default_value' => 'text',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6480a180c2086',
            'label' => 'Padding',
            'name' => 'padding',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6480a180c2087',
                    'label' => 'Top',
                    'name' => 'top',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6480a180c2088',
                    'label' => 'Bottom',
                    'name' => 'bottom',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6480a180c2089',
                    'label' => '',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<strong>Set a value 0-5.</strong>
0 = 0px | 1 = 20px | 2 = 40px | 3 = 60px | 4 = 80px | 5 = 100px',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_644a4f64d93e6',
            'label' => 'Split One',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_644a577d3e117',
            'label' => '',
            'name' => 'split_one_content',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_646232b569752',
                    'label' => 'Carousel',
                    'name' => 'carousel_content',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6448fb99386fc',
                                'operator' => '==',
                                'value' => 'carousel',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_646235a06975b',
                            'label' => 'Content',
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                            'parent_repeater' => 'field_646232b569752',
                        ),
                        array(
                            'key' => 'field_6501cbfe9f2cf',
                            'label' => 'Buttons',
                            'name' => 'buttons',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'Add Button',
                            'rows_per_page' => 20,
                            'parent_repeater' => 'field_646232b569752',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6501cbff9f2d0',
                                    'label' => '',
                                    'name' => 'button',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_643e971cd877b',
                                                'operator' => '==',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => '',
                                    'parent_repeater' => 'field_6501cbfe9f2cf',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6501cbff9f2d1',
                                            'label' => 'Enabled',
                                            'name' => 'enabled',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 1,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cbff9f2d2',
                                            'label' => 'Open In New Tab',
                                            'name' => 'open_in_new_tab',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cbff9f2d3',
                                            'label' => 'Background',
                                            'name' => 'colour',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'primary' => 'Primary',
                                                'secondary' => 'Secondary',
                                                'tertiary' => 'Tertiary',
                                                'light-grey' => 'Light Grey',
                                                'white' => 'White',
                                                'outline-primary' => 'Outline - Primary',
                                                'outline-secondary' => 'Outline - Secondary',
                                                'outline-tertiary' => 'Outline - Tertiary',
                                                'outline-light-grey' => 'Outline - Light Grey',
                                                'outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'primary',
                                            'return_format' => '',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cbff9f2d4',
                                            'label' => 'Hover',
                                            'name' => 'hover',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'hover-primary' => 'Primary',
                                                'hover-secondary' => 'Secondary',
                                                'hover-tertiary' => 'Tertiary',
                                                'hover-light-grey' => 'Light Grey',
                                                'hover-white' => 'White',
                                                'hover-outline-primary' => 'Outline - Primary',
                                                'hover-outline-secondary' => 'Outline - Secondary',
                                                'hover-outline-tertiary' => 'Outline - Tertiary',
                                                'hover-outline-light-grey' => 'Outline - Light Grey',
                                                'hover-outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'hover-secondary',
                                            'return_format' => '',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cbff9f2d5',
                                            'label' => 'Display Text',
                                            'name' => 'display_text',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '75',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cbff9f2d6',
                                            'label' => 'Link',
                                            'name' => 'link',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '75',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_644a57ba3e118',
                    'label' => '',
                    'name' => 'image_content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6448fb99386fc',
                                'operator' => '==',
                                'value' => 'image',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_644a57ce3e119',
                            'label' => 'Image',
                            'name' => 'image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'preview_size' => 'thumbnail',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_64e5bd36abcf6',
                    'label' => '',
                    'name' => 'image_carousel_content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6448fb99386fc',
                                'operator' => '==',
                                'value' => 'image_carousel',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_64e5be0eabcfa',
                            'label' => 'Images',
                            'name' => 'image_gallery',
                            'aria-label' => '',
                            'type' => 'gallery',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min' => '',
                            'max' => '',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'insert' => 'append',
                            'preview_size' => 'medium',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6491a2b4d5003',
                    'label' => 'Set the map centre point',
                    'name' => 'map_content',
                    'aria-label' => '',
                    'type' => 'google_map',
                    'instructions' => '<b>IMPORTANT</b></br>
If you are using this block on a single Events page you do not need to set the map location here.</br>
Map location will be taken from the <b>Google Maps coordinates</b> field under <b>Product data</b> > <b>Event Settings</b>',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6448fb99386fc',
                                'operator' => '==',
                                'value' => 'map',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'center_lat' => '',
                    'center_lng' => '',
                    'zoom' => '',
                    'height' => '',
                ),
                array(
                    'key' => 'field_644a5876831dd',
                    'label' => '',
                    'name' => 'text_content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6448fb99386fc',
                                'operator' => '==',
                                'value' => 'text',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_644a5892831de',
                            'label' => 'Title',
                            'name' => 'title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '70',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_9094j201afcc2',
                            'label' => 'Title Settings',
                            'name' => 'title_settings',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_9094j201afcc3',
                                    'label' => 'Importance',
                                    'name' => 'importance',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'h1' => 'H1',
                                        'h2' => 'H2',
                                        'h3' => 'H3',
                                        'h4' => 'H4',
                                    ),
                                    'default_value' => 'h2',
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'field_9094j201afcc4',
                                    'label' => 'Colour',
                                    'name' => 'colour',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'primary' => 'Primary',
                                        'secondary' => 'Secondary',
                                        'light-grey' => 'Light Grey',
                                        'white' => 'White',
                                        'black' => 'Black',
                                    ),
                                    'default_value' => 'primary',
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_644a589a831df',
                            'label' => 'Content',
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        array(
                            'key' => 'field_6501cc579f2d7',
                            'label' => 'Buttons',
                            'name' => 'buttons',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'Add Button',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6501cc589f2d8',
                                    'label' => '',
                                    'name' => 'button',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'block',
                                    'parent_repeater' => 'field_6501cc579f2d7',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6501cc589f2d9',
                                            'label' => 'Enabled',
                                            'name' => 'enabled',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 1,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc589f2da',
                                            'label' => 'Open In New Tab',
                                            'name' => 'open_in_new_tab',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc589f2db',
                                            'label' => 'Background',
                                            'name' => 'colour',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'primary' => 'Primary',
                                                'secondary' => 'Secondary',
                                                'tertiary' => 'Tertiary',
                                                'light-grey' => 'Light Grey',
                                                'white' => 'White',
                                                'outline-primary' => 'Outline - Primary',
                                                'outline-secondary' => 'Outline - Secondary',
                                                'outline-tertiary' => 'Outline - Tertiary',
                                                'outline-light-grey' => 'Outline - Light Grey',
                                                'outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'primary',
                                            'return_format' => '',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc589f2dc',
                                            'label' => 'Hover',
                                            'name' => 'hover',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'hover-primary' => 'Primary',
                                                'hover-secondary' => 'Secondary',
                                                'hover-tertiary' => 'Tertiary',
                                                'hover-light-grey' => 'Light Grey',
                                                'hover-white' => 'White',
                                                'hover-outline-primary' => 'Outline - Primary',
                                                'hover-outline-secondary' => 'Outline - Secondary',
                                                'hover-outline-tertiary' => 'Outline - Tertiary',
                                                'hover-outline-light-grey' => 'Outline - Light Grey',
                                                'hover-outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'hover-secondary',
                                            'return_format' => '',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc589f2dd',
                                            'label' => 'Display Text',
                                            'name' => 'display_text',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '50',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc589f2de',
                                            'label' => 'Link',
                                            'name' => 'link',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '50',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_644a570b66173',
            'label' => 'Split Two',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_644a59870544f',
            'label' => '',
            'name' => 'split_two_content',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_64623ce3d257c',
                    'label' => 'Carousel',
                    'name' => 'carousel_content',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_644a4fb9d93e8',
                                'operator' => '==',
                                'value' => 'carousel',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_64623ce3d257e',
                            'label' => 'Content',
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                            'parent_repeater' => 'field_64623ce3d257c',
                        ),
                        array(
                            'key' => 'field_6501cc959f2df',
                            'label' => 'Buttons',
                            'name' => 'buttons',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'Add Button',
                            'rows_per_page' => 20,
                            'parent_repeater' => 'field_64623ce3d257c',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6501cc969f2e0',
                                    'label' => '',
                                    'name' => 'button',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_643e971cd877b',
                                                'operator' => '==',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => '',
                                    'parent_repeater' => 'field_6501cc959f2df',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6501cc969f2e1',
                                            'label' => 'Enabled',
                                            'name' => 'enabled',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 1,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc969f2e2',
                                            'label' => 'Open In New Tab',
                                            'name' => 'open_in_new_tab',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc969f2e3',
                                            'label' => 'Background',
                                            'name' => 'colour',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'primary' => 'Primary',
                                                'secondary' => 'Secondary',
                                                'tertiary' => 'Tertiary',
                                                'light-grey' => 'Light Grey',
                                                'white' => 'White',
                                                'outline-primary' => 'Outline - Primary',
                                                'outline-secondary' => 'Outline - Secondary',
                                                'outline-tertiary' => 'Outline - Tertiary',
                                                'outline-light-grey' => 'Outline - Light Grey',
                                                'outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'primary',
                                            'return_format' => '',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc969f2e4',
                                            'label' => 'Hover',
                                            'name' => 'hover',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'hover-primary' => 'Primary',
                                                'hover-secondary' => 'Secondary',
                                                'hover-tertiary' => 'Tertiary',
                                                'hover-light-grey' => 'Light Grey',
                                                'hover-white' => 'White',
                                                'hover-outline-primary' => 'Outline - Primary',
                                                'hover-outline-secondary' => 'Outline - Secondary',
                                                'hover-outline-tertiary' => 'Outline - Tertiary',
                                                'hover-outline-light-grey' => 'Outline - Light Grey',
                                                'hover-outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'hover-secondary',
                                            'return_format' => '',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc969f2e5',
                                            'label' => 'Display Text',
                                            'name' => 'display_text',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '75',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501cc969f2e6',
                                            'label' => 'Link',
                                            'name' => 'link',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '75',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_644a598705450',
                    'label' => '',
                    'name' => 'image_content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_644a4fb9d93e8',
                                'operator' => '==',
                                'value' => 'image',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_644a598705451',
                            'label' => 'Image',
                            'name' => 'image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'preview_size' => 'thumbnail',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_64e5c2de62757',
                    'label' => '',
                    'name' => 'image_carousel_content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6448fb99386fc',
                                'operator' => '==',
                                'value' => 'image_carousel',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_64e5c2df62759',
                            'label' => 'Images',
                            'name' => 'image_gallery',
                            'aria-label' => '',
                            'type' => 'gallery',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min' => '',
                            'max' => '',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'insert' => 'append',
                            'preview_size' => 'medium',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6491a262d5002',
                    'label' => 'Set the map centre point',
                    'name' => 'map_content',
                    'aria-label' => '',
                    'type' => 'google_map',
                    'instructions' => '<b>IMPORTANT</b></br>
If you are using this block on a single Events page you do not need to set the map location here.</br>
Map location will be taken from the <b>Google Maps coordinates</b> field under <b>Product data</b> > <b>Event Settings</b>',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_644a4fb9d93e8',
                                'operator' => '==',
                                'value' => 'map',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'center_lat' => '',
                    'center_lng' => '',
                    'zoom' => '',
                    'height' => '',
                ),
                array(
                    'key' => 'field_644a598705452',
                    'label' => '',
                    'name' => 'text_content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_644a4fb9d93e8',
                                'operator' => '==',
                                'value' => 'text',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_644a598705454',
                            'label' => 'Title',
                            'name' => 'title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '70',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_4938r201afcc2',
                            'label' => 'Title Settings',
                            'name' => 'title_settings',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_4938r201afcc3',
                                    'label' => 'Importance',
                                    'name' => 'importance',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'h1' => 'H1',
                                        'h2' => 'H2',
                                        'h3' => 'H3',
                                        'h4' => 'H4',
                                    ),
                                    'default_value' => 'h2',
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'field_4938r201afcc4',
                                    'label' => 'Colour',
                                    'name' => 'colour',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'primary' => 'Primary',
                                        'secondary' => 'Secondary',
                                        'light-grey' => 'Light Grey',
                                        'white' => 'White',
                                        'black' => 'Black',
                                    ),
                                    'default_value' => 'primary',
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_644a598705455',
                            'label' => 'Content',
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        array(
                            'key' => 'field_6501ccd69f2e7',
                            'label' => 'Buttons',
                            'name' => 'buttons',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => false,
                            'conditional_logic' => false,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 0,
                            'max' => 0,
                            'rows_per_page' => 20,
                            'layout' => 'table',
                            'button_label' => 'Add Row',
                            'collapsed' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6501ccd69f2e8',
                                    'label' => '',
                                    'name' => 'button',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => false,
                                    'conditional_logic' => false,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'block',
                                    'parent_repeater' => 'field_6501ccd69f2e7',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6501ccd69f2e9',
                                            'label' => 'Enabled',
                                            'name' => 'enabled',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 1,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501ccd69f2ea',
                                            'label' => 'Open In New Tab',
                                            'name' => 'open_in_new_tab',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501ccd69f2eb',
                                            'label' => 'Background',
                                            'name' => 'colour',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'primary' => 'Primary',
                                                'secondary' => 'Secondary',
                                                'tertiary' => 'Tertiary',
                                                'light-grey' => 'Light Grey',
                                                'white' => 'White',
                                                'outline-primary' => 'Outline - Primary',
                                                'outline-secondary' => 'Outline - Secondary',
                                                'outline-tertiary' => 'Outline - Tertiary',
                                                'outline-light-grey' => 'Outline - Light Grey',
                                                'outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'primary',
                                            'return_format' => 'value',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6501ccd69f2ec',
                                            'label' => 'Hover',
                                            'name' => 'hover',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => false,
                                            'wrapper' => array(
                                                'width' => '25',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                'hover-primary' => 'Primary',
                                                'hover-secondary' => 'Secondary',
                                                'hover-tertiary' => 'Tertiary',
                                                'hover-light-grey' => 'Light Grey',
                                                'hover-white' => 'White',
                                                'hover-outline-primary' => 'Outline - Primary',
                                                'hover-outline-secondary' => 'Outline - Secondary',
                                                'hover-outline-tertiary' => 'Outline - Tertiary',
                                                'hover-outline-light-grey' => 'Outline - Light Grey',
                                                'hover-outline-white' => 'Outline - White',
                                            ),
                                            'default_value' => 'hover-secondary',
                                            'return_format' => 'value',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                        array(
                                            'key' => 'field_6512b56b8643a',
                                            'label' => 'Display Text',
                                            'name' => 'display_text',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '50',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                        array(
                                            'key' => 'field_6512b57f8643b',
                                            'label' => 'Link',
                                            'name' => 'link',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '50',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'min' => '',
    'max' => '',
);
