<?php
return array(
    'key' => 'layout_635149ba605ce',
    'name' => 'wysiwyg',
    'label' => 'WYSIWYG',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_64410baea6ea7',
            'label' => 'Settings',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_64410bcda6ea9',
            'label' => 'Background',
            'name' => 'background',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'primary' => 'Primary',
                'secondary' => 'Secondary',
                'tertiary' => 'Tertiary',
                'light-grey' => 'Light Grey',
                'white' => 'White',
            ),
            'default_value' => 'white',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_64536ec1fc703',
            'label' => 'Content Width',
            'name' => 'content_width',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'full' => 'Full',
                'three-quarter' => 'Three Quarter',
                'half' => 'Half',
            ),
            'default_value' => 'full',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6453716c8bb4f',
            'label' => 'Content Layout',
            'name' => 'content_layout',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => 'Left',
                'center' => 'Centre',
                'right' => 'Right',
            ),
            'default_value' => 'left',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6480a1dbc208e',
            'label' => 'Padding',
            'name' => 'padding',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6480a1dbc208f',
                    'label' => 'Top',
                    'name' => 'top',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6480a1dbc2090',
                    'label' => 'Bottom',
                    'name' => 'bottom',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'min' => 0,
                    'max' => 5,
                    'placeholder' => '',
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6480a1dbc2091',
                    'label' => '',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<strong>Set a value 0-5.</strong>
0 = 0px | 1 = 20px | 2 = 40px | 3 = 60px | 4 = 80px | 5 = 100px',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_64410bb8a6ea8',
            'label' => 'Content',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_635149c0605cf',
            'label' => '',
            'name' => 'wysiwyg',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'field_6453b56026168',
            'label' => 'Buttons',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6502c774d169e',
            'label' => '',
            'name' => 'buttons',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'table',
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Button',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_6502c775d169f',
                    'label' => '',
                    'name' => 'button',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'parent_repeater' => 'field_6502c774d169e',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6502c775d16a0',
                            'label' => 'Enabled',
                            'name' => 'enabled',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 1,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'field_6502c775d16a1',
                            'label' => 'Open In New Tab',
                            'name' => 'open_in_new_tab',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'field_6502c775d16a2',
                            'label' => 'Background',
                            'name' => 'colour',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'primary' => 'Primary',
                                'secondary' => 'Secondary',
                                'tertiary' => 'Tertiary',
                                'light-grey' => 'Light Grey',
                                'white' => 'White',
                                'outline-primary' => 'Outline - Primary',
                                'outline-secondary' => 'Outline - Secondary',
                                'outline-tertiary' => 'Outline - Tertiary',
                                'outline-light-grey' => 'Outline - Light Grey',
                                'outline-white' => 'Outline - White',
                            ),
                            'default_value' => 'primary',
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6502c775d16a3',
                            'label' => 'Hover',
                            'name' => 'hover',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'hover-primary' => 'Primary',
                                'hover-secondary' => 'Secondary',
                                'hover-tertiary' => 'Tertiary',
                                'hover-light-grey' => 'Light Grey',
                                'hover-white' => 'White',
                                'hover-outline-primary' => 'Outline - Primary',
                                'hover-outline-secondary' => 'Outline - Secondary',
                                'hover-outline-tertiary' => 'Outline - Tertiary',
                                'hover-outline-light-grey' => 'Outline - Light Grey',
                                'hover-outline-white' => 'Outline - White',
                            ),
                            'default_value' => 'hover-secondary',
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6502c775d16a4',
                            'label' => 'Display Text',
                            'name' => 'display_text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_6502c775d16a5',
                            'label' => 'Link',
                            'name' => 'link',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                    ),
                ),
            ),
        ),
    ),
    'min' => '',
    'max' => '',
);